### ISSUE TITLE
Add fill in the blanks examples

### ISSUE THREAD

**Issue by phoebem** [capstone-lingo-2016/open-fluency2#44]

**Comment by MattSilva** [comment]
I added one example to the QuizEditor branch. https://github.com/capstone-lingo-2016/open-fluency2/commit/b496ed1466e6ac78af9cc598d757f5a9afeb86cc

**Comment by danielfrench** [comment]
I added an example to a quiz as well.  I think we can close this one out.  We will just have to add information in our documentation/final milestone documents.
