### ISSUE TITLE
ExportData missing functionality

### ISSUE THREAD

**Issue by phoebem** [capstone-lingo-2016/open-fluency2#59]
When logged in as researcher and click on each exportable link,
The link for CSV under "Quiz Data" fails:

| Error 2016-04-11 22:59:20,604 [http-bio-8080-exec-5] ERROR errors.GrailsExceptionResolver  - MissingPropertyException occurred when processing request: [GET] /OpenFluency/dataAccess/exportQuizData - parameters:
extension: csv
format: csv
No such property: flashcard for class: com.openfluency.course.Question. Stacktrace follows:
Message: No such property: flashcard for class: com.openfluency.course.Question

**Comment by MattSilva** [comment]
This is the same as https://github.com/capstone-lingo-2016/open-fluency2/issues/58
Was fixed in commit: https://github.com/capstone-lingo-2016/open-fluency2/commit/9fc124c5c57d1bae051a507b943c8a7e9ec3b4b7
