### ISSUE TITLE
Each quiz grade in the grade database entry is entered twice.

### ISSUE THREAD

**Issue by phoebem** [capstone-lingo-2016/open-fluency2#80]
"Select \* from grade" produces 6 records when I took 3 quizzes (once each), This may mess up researcher data.
ID      VERSION     CORRECT_ANSWERS     DATE_CREATED    LAST_UPDATED    NUMBER_OF_QUESTIONS     QUIZ_ID     USER_ID  
1   0   8   2016-04-24 20:32:54.986 2016-04-24 20:32:54.986 8   6   2
2   0   8   2016-04-24 20:32:55.006 2016-04-24 20:32:55.006 8   6   2
3   0   4   2016-04-24 20:33:54.942 2016-04-24 20:33:54.942 4   4   2
4   0   4   2016-04-24 20:33:54.951 2016-04-24 20:33:54.951 4   4   2
5   0   1   2016-04-24 20:34:21.855 2016-04-24 20:34:21.855 5   1   2
6   0   1   2016-04-24 20:34:21.866 2016-04-24 20:34:21.866 5   1   2
(6 rows, 1 ms)

**Comment by MattSilva** [comment]
I noticed this too and I spent some time this past weekend trying to figure out why GORM is saving it this way. However, I haven't noticed this double saving affecting the actual functionality in any way. We might have to discuss whether this issue has high enough priority to fix before Milestone 3.

**Comment by MattSilva** [comment]
This issue should be fixed in commit c5ba402727f34fc17a5ff6cbe932ac00e22a6d66
